### ISSUE TITLE
Latex, Katex support

### ISSUE THREAD

**Issue by snow-abstraction** [getzola/even#26]
I started from scratch and enabled Katex and tried an example
```
{% katex(block=true) %}
\begin{matrix}
   a & b \\
   c & d
\end{matrix}
{% end %} 
```
that renders correctly when entered into the "Type an expression:" box on https://katex.org/. But when I build and server my site, instead of '&' being used for alignment they are rendered as `amp;`:

![image](https://user-images.githubusercontent.com/8106593/56385959-dbf12400-6220-11e9-9162-985da9e1cf52.png)

I am able render correctly things like `A_{ij} = ...`

Is this a bug or a configuration issue on my side?

**Comment by snow-abstraction** [comment]
I dug into my issue some more but I didn't manage to solve. 

I looked at source of the rendered page in chrome and I found this:

![image](https://user-images.githubusercontent.com/8106593/56387777-7e130b00-6225-11e9-9b46-208fdf682f8f.png)

The shortcode for Katex is
`<script type="math/tex{% if block %};mode=display{% endif %}">{{body}}</script>`
from the file
`themes/even/templates/shortcodes/katex.html`
but I don't know how to fix it.

**Comment by Keats** [comment]
Try body | safe in the short code as tera is escaping some of the text

**Comment by snow-abstraction** [comment]
@Keats Thanks. That worked. I also testing some more things from
https://katex.org/docs/supported.html
that had '#' or '&' in them and the ones with '&' needed `body | safe` to render correctly. Everything else worked as expected.

Would a PR to change the short code be appropriate? Or would PR towards the even documentation being better for now? I am guessing that a better long term solution would be for tera should understand not to escape "&" if the `script` tag has the attribute `type="math/tex"` 

Feel free to close the issue. I would but I don't know the project policy.

**Comment by snow-abstraction** [comment]
Thanks @Keats
