### ISSUE TITLE
Code blocks background isn't changing with `highlight_theme`

### ISSUE THREAD

**Issue by WaffleLapkin** [getzola/even#46]
With `even` theme used, the background of code blocks isn't changing, when `highlight_theme` is changed. 

<details><summary>Screenshot (`gruvbox-dark`)</summary>

![image](https://user-images.githubusercontent.com/38225716/123508595-0b114480-d679-11eb-8d59-6ae091e28922.png)

</details>
<details><summary>Screenshot (`nord`)</summary>

![image](https://user-images.githubusercontent.com/38225716/123508605-1ebcab00-d679-11eb-943a-19bde7c9a851.png)

</details>

Is there a way to fix this? Currently, code blocks are almost impossible to read.

**Comment by Keats** [comment]
https://github.com/getzola/even/blob/master/sass/_main.scss#L39-L44 should probably be changed. It's meant for inline code but it also applies to the codeblocks.
